# Use the official Open WebUI image with CUDA support
FROM ghcr.io/open-webui/open-webui:cuda
# If you don't need GPU support, use:
# FROM ghcr.io/open-webui/open-webui:main

# Expose the port Open WebUI is listening on (as per the documentation)
EXPOSE 8080

# You can add any custom commands here if needed, for example:
# USER open-webui
# CMD ["start-server.sh", "--option1", "value1"]
